[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:api"
watchPatterns = ["apps/api/**", "packages/**"]

[deploy]
startCommand = "cd apps/api && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3001"