[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[services.web]
source = "apps/web"
build.buildCommand = "npm install && npm run build"
deploy.startCommand = "npm start"

[services.api]
source = "apps/api"
build.buildCommand = "npm install && npm run build"
deploy.startCommand = "npm start"