# Railway configuration for project management SaaS

[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Web Frontend Service
[[services]]
name = "web"
source = "."
buildCommand = "npm install && npm run build:web"
startCommand = "npm run start:web"
variables = { NODE_ENV = "production", NIXPACKS_BUILD_CMD = "npm install && npm run build:web" }

# API Backend Service  
[[services]]
name = "api"
source = "."
buildCommand = "npm install && npm run build:api && npm run db:generate"
startCommand = "npm run start:api"
variables = { NODE_ENV = "production", NIXPACKS_BUILD_CMD = "npm install && npm run build:api && npm run db:generate" }