[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run railway:setup && npm run build:web"
watchPatterns = ["apps/web/**", "packages/**"]

[deploy]
startCommand = "cd apps/web && npm start"

[env]
NODE_ENV = "production"
PORT = "3000"