[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cd ../.. && npm ci',
  'cd ../../packages/database && npm run db:generate'
]

[phases.build]
cmds = [
  'cd ../.. && npm run build:api'
]

[start]
cmd = 'cd apps/api && npm start'

[variables]
NODE_ENV = 'production'
PORT = '3001'